apiVersion: v1
kind: Secret
metadata: { name: {{ include "verosys.name" . }}-secret }
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
